name: GNU RISC-V toolchain Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-24.04
    env:
      CC: riscv64-linux-gnu-gcc-14
      CXX: riscv64-linux-gnu-g++-14

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++-14-riscv64-linux-gnu git libluajit-5.1-dev
        git submodule update --init --recursive --depth=1

    - name: Build all examples
      working-directory: ${{github.workspace}}
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSTRIPPED=ON
        cmake --build build --parallel 8
